# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bdcc90da894b69f6f98eebd73a398e93741b2d51d9b89dd96bde15d64ad9d2aadbfd43287b06b7cf698e701a827720eab47ea0d8fe4e8af0cfac78cfb08dc522

test:
  secret_key_base: 760f7bbf87cbc91355fb0c0ceafcb32ae5234ab835863cbb88312dda50ed49ba02f977d84cccd5b21a58350f1bc67dcf1376700672e918c046e3f4daa3c147ba

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
